name: Build debug apk

on:
  [workflow_dispatch]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout OsmAnd
      uses: actions/checkout@v7
      with:
        path: android
    - name: checkout OsmAnd-resources
      uses: actions/checkout@v7
      with:
        repository: osmandapp/OsmAnd-resources
        path: resources
    - name: checkout OsmAnd-core
      uses: actions/checkout@v7
      with:
        repository: osmandapp/OsmAnd-core
        path: core
    - name: checkout OsmAnd-core-legacy
      uses: actions/checkout@v7
      with:
        repository: osmandapp/OsmAnd-core-legacy
        path: core-legacy
    - name: checkout OsmAnd-build
      uses: actions/checkout@v7
      with:
        repository: osmandapp/OsmAnd-build
        path: build
    - name: checkout OsmAnd-tools
      uses: actions/checkout@v7
      with:
        repository: osmandapp/OsmAnd-tools
        path: tools
    - name: checkout OsmAnd-misc
      uses: actions/checkout@v7
      with:
        repository: osmandapp/OsmAnd-misc
        path: misc

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      working-directory: ./android
      run: chmod +x gradlew
    - name: Patch memory requirements
      working-directory: ./android
      run: printf "\norg.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8\n" >> gradle.properties
    - name: Build with Gradle
      working-directory: ./android
      run: ./gradlew assembleAndroidFullOpenglFatDebug
    - name: Rename APK
      working-directory: ./android
      run: |
        mkdir -p OsmAnd/build/outputs/apk/debug_collected
        find OsmAnd/build/outputs/apk -name "*.apk" -exec cp {} OsmAnd/build/outputs/apk/debug_collected/ \;
    - name: Archive APK
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: android/OsmAnd/build/outputs/apk/debug_collected/*.apk
        retention-days: 90
